package com.example.bikelove.cloud.authorization

object AuthorizationConst {
    const val SHARED_PREFERENCES_AUTHORIZATION_KEY = "SHARED_PREFERENCES_AUTHORIZATION_KEY"
    const val SHARED_PREFERENCES_TOKEN_KEY = "SHARED_PREFERENCES_AUTHORIZATION_KEY"
    const val SHARED_PREFERENCES_REFRESH_TOKEN_KEY = "SHARED_PREFERENCES_REFRESH_TOKEN_KEY"
}